name: GitHub Workflow

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write

jobs:
  CI-CD:
    uses: BrunoBrasolin/workflow-template/.github/workflows/angular-gh_pages.yml@main
    with:
      applicationName: front-gamidas
      cname: gamidas.dev.br
